### ISSUE TITLE
Add a rebuild button for a whole commit

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/ocaml-ci#163]
It would be very useful to add a rebuild button on each `github/<user>/<repo>/commit/<hash>/` pages, for the whole pipeline used on this commit to be rebuilt.

**Comment by talex5** [comment]
Why? It seems unlikely that all variants will suffer the same build worker failure.

Though a more general bulk-rebuild feature would be nice (e.g. *rebuild everything with "Disk full" in the log*).

**Comment by talex5** [comment]
We now have a bulk-rebuild feature on the `/query` page of the admin UI. Maybe that's enough for what you need? Please reopen if not.

**Comment by kit-ty-kate** [comment]
Here is an example where this is not enough: https://github.com/ocaml/opam-repository/pull/19397#issuecomment-913163748 Could this be reopened? I don't have the rights to do it myself.

**Comment by kit-ty-kate** [comment]
> We now have a bulk-rebuild feature on the `/query` page of the admin UI. Maybe that's enough for what you need?

There are no filters per commits so I cannot do anything there.

**Comment by kit-ty-kate** [comment]
Having to make an empty commit for every new PRs in opam-repository when something breaks down in the cluster is really annoying and it would be nice to have an accessible option to at least rebuild every failing builds

**Comment by mseri** [comment]
Yes, this would be really useful. And also an equivalent version that only rebuilds the failed jobs

**Comment by novemberkilo** [comment]
Documenting the plan:

1. A commit can be rebuilt if there are jobs in state Aborted | Failed | Undefined and there are no jobs that are in state Active | NotStarted (this means that the Cancel button, that appears only when there are Active | Not Started jobs, cannot appear at the same time as a Rebuild button)
2. When a commit can be rebuilt, show two buttons - "Rebuild Failed" and "Rebuild All" so that the user has the choice of rebuilding only the failed jobs, or to rebuild the entire commit.

**Comment by novemberkilo** [comment]
Can this issue be closed now? // @tmcgilchrist @kit-ty-kate

**Comment by maiste** [comment]
Closing as it has been done in https://github.com/ocurrent/ocaml-ci/pull/469.
