### ISSUE TITLE
Have a way of setting custom installation and testing steps

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/ocaml-ci#22]
Currently ocaml-ci uses a simple opam install -t to install and test the packages. However there might be pre-install or pre-tests steps or any kind of custom steps that we'd want the CI to do. For this, some sort of config file might be useful. This configure file could also serve to set the system we would want the packages to be tested on in the future if we want to test more than the current default (alpine)

**Comment by avsm** [comment]
I'd like to avoid having a config file if at all possible, and derive the information from existing metadata (and refine this metadata if its not supported for some reason). Could you use this issue to give a few pointers to some custom steps not supported?

Note that for things like more base image support, or the OCaml matrix, we should just add those to ocaml-ci for all packages to use.

**Comment by CraigFe** [comment]
As far as I'm aware, we don't have specific use-cases for custom configuration at the moment (and the default test footprint of OCaml-CI has increased quite a bit since the issue was made), so I'll close this issue for now.

I'm agreed with @avsm that, to a first approximation, any 'custom' CI requirements of projects should  be: 

- added to `ocaml-ci` for every package to use (conditionally executed according to some heuristic, if need-be); or
 - encoded into `dune` rules so that `ocaml-ci` can invoke them with the same API as other projects. We've had quite a bit of success already with converting "non-compliant" repositories like OCamlformat to use the standard API.
