### ISSUE TITLE
Update immediately to opam-repository changes

### ISSUE THREAD

**Issue by talex5** [ocurrent/ocaml-ci#26]
At the moment, we update the base Docker images once a week, and this brings in the latest opam-repository changes. However, it would be good to be able to test against new releases immediately.

The problem with doing `opam update` before each job is that we would lose the benefits of caching, because the layer hash would be different each time.

Some options:

1. If opam could extract from a repository just the information it needed, we could throw away the repository and just keep that. Then repository changes would invalidate the cache only if something we needed changed. There doesn't seem to be any way to do that, though.

2. We could add a configuration file where the user specifies the mimimum repository commit they need. e.g.
   ```
    (ocaml-ci
     (minimum-opam-commit abcd123e))
   ```
   If the repository doesn't contain that commit then we update to it.

**Comment by talex5** [comment]
Note that you can work around this problem by adding git-submodule(s) with the versions you need. Then the CI will test against those.

**Comment by avsm** [comment]
I don't think that the second suggestion is practical, since there is no clear correspondence in the order of opam-repo commits (that is, there is no guarantee that all subsequent commits after a minimum-opam-commit would actually work).  The only thing that information would tell the CI is that _one particular_ opam-repo revision was known to work -- and even then, that might fail with different solver information such as os/arch/ocaml-version.

**Comment by hannesm** [comment]
the unknown update cycle of the opam-repository in the ci images makes it very non-intuitive to use for me (esp. since I can't find any documentation thereof, neither how to manually update the opam repository, nor which opam-repository commit a CI run used), and I'd appreciate any solution (such as `(minimum-opam-commit abcd123e)` would work fine for me).

thanks.

**Comment by talex5** [comment]
Since #167 and #173 were merged, the CI now checks for changes to opam-repository hourly and should start rebuilding anything that needs updating within about 30 minutes of that.

**Comment by talex5** [comment]
Fixed in #194. The CI gets a webhook event when opam-repository updates and starts rebuilding things immediately.
