### ISSUE TITLE
Dream UI fails to reconnect after lost connection

### ISSUE THREAD

**Issue by talex5** [ocurrent/ocaml-ci#519]
If you restart ocaml-ci, the Dream web UI will just produce 500 errors until it is restarted.

To answer this question in the source code:
https://github.com/ocurrent/ocaml-ci/blob/ac53229028ff6e7ffb2275bcc4dd6344a4aca534/web-ui/backend.ml#L25-L26

1. Run the engine:
   ```sh
   dune exec -- ocaml-ci-service --confirm=harmless ... --capnp-listen-address=tcp:127.0.0.1:3000
   ```
2. Run the web UI:
   ```sh
   dune exec -- ocaml-ci-web -v --backend ./capnp-secrets/ocaml-ci-admin.cap ...
   ```
3. Kill the engine. Verify that the web UI is showing errors.
4. Run the engine again. Wait 5s. Verify that the web UI is happy again.

**Comment by moyodiallo** [comment]
I've already dealt with multicore-ci [(fix reference)](https://github.com/ocurrent/ocaml-multicore-ci/commit/52c7fd122e4060734e0cf43876f4de0ddb7228d5). 

The issue is the `Backend.connect` function return a value (`t.ci`) in order `Backend.t`. Even if the service is reconnected, the service has no access to the new `t.ci` value, because the old `t.ci` is always used.

**Comment by tmcgilchrist** [comment]
Fixed https://github.com/ocurrent/ocaml-ci/pull/521
