### ISSUE TITLE
Build history shows incorrect build statuses

### ISSUE THREAD

**Issue by novemberkilo** [ocurrent/ocaml-ci#703]
The build statuses of historical builds are wrong. Here is an example:

Build history page for `master` of ocaml-ci on 2022-12-23 - Note that `fc937b` is showing as pending

![Screenshot 2022-12-23 at 12 39 04 pm](https://user-images.githubusercontent.com/181086/209254050-79baaaf5-7204-4077-8f27-c5089d9d2dc5.png)

However, this is not correct. Following the link to the build of `fc937b` shows the build has completed and should be in state `Failed` -- Further, the build page of this commit shows a default (or unknown) build status.

![Screenshot 2022-12-23 at 12 39 59 pm](https://user-images.githubusercontent.com/181086/209254440-178587d4-0ce3-45ae-8422-bbd8b46bf886.png)

**Comment by novemberkilo** [comment]
Results of investigation: It is possible that this is because of flaky builds around this time (timeouts caused by workers hanging). I have walked through the logic around how the status of a ref is derived from a summary of the build - this has not changed in a long time so I am discounting this as being the source of the issue. 

Leaving open for further investigation.

**Comment by novemberkilo** [comment]
Partial (??) fix in #705 -- fixing an error in handling a cache miss.

**Comment by novemberkilo** [comment]
Build statuses of historical builds are showing as running when they are finished. Suggest removing the Commit_cache and Aggregate structure and using the db directly.

**Comment by maiste** [comment]
After investigation, this state happens when a _job_ is `auto-cancelled` by `Current_cache`. As we don't go through the `record` function, it never records the fact that it has been cancelled.

 I'm working on a solution to call `Current.Job.on_cancel`  in __cluster_build.ml__ that records the fact that it has been auto-cancelled by adding a new entry to the database if the previous `status` is `Pending`.
