### ISSUE TITLE
Support build status badges

### ISSUE THREAD

**Issue by CraigFe** [ocurrent/ocaml-ci#91]
Would be nice to have something colourful to put in `README`s. Likely requires exposing new per-repository endpoints which check the build status and redirect to an appropriate badge. For example (courtesy of @emillon):

- https://img.shields.io/badge/ocaml--ci-builds-informational?logo=ocaml&style=for-the-badge
- https://img.shields.io/badge/ocaml--ci-passing-success?logo=ocaml&style=for-the-badge
- https://img.shields.io/badge/ocaml--ci-failing-critical?logo=ocaml&style=for-the-badge

**Comment by emillon** [comment]
Note that if we go with shields.io, they recommend not redirecting to the static API but rather using this API: (for reasons outlined on that page) https://shields.io/endpoint. Once again, if we go with shields, writing an integration for them so that `shields.io/ocaml-ci/::user/repo` works (in a second step) is not too hard.
